spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:51269/railway?userSSl=false
    username: root
    password: Ced21C3BCaCH-BffCdGc-1bCEAGF6d-B
    
#JPA settings
  jpa:
    hibernate:
      ddl-auto: none